# Query to create summary day one vitals table
def summary_joined_vitals_query():
    return '''
    DROP TABLE IF EXISTS derived.summary_joined_vitals CASCADE;
    CREATE TABLE derived.summary_joined_vitals AS 
        SELECT "derived"."summary_day1_vitals"."Facility Name" AS "Facility Name",
"derived"."summary_day1_vitals"."NeoTreeID" AS "NeoTreeID",
Date("derived"."summary_day1_vitals"."Date") AS "Date",
"derived"."summary_day1_vitals"."Length of stay" AS "Length of stay",
"derived"."summary_day1_vitals"."Neonatal Sepsis Study" AS "Neonatal Sepsis Study",
"derived"."summary_day1_vitals"."Day of the Week" AS "Day of the Week",
"derived"."summary_day1_vitals"."Public Holiday" AS "Public Holiday",
"derived"."summary_day1_vitals"."No of Day Shift Nurses" AS "No of Day Shift Nurses",
"derived"."summary_day1_vitals"."No of Night Shift Nurses" AS "No of Night Shift Nurses",
"derived"."summary_day1_vitals"."No of Countious Shift Nurses" AS "No of Countious Shift Nurses",
"derived"."summary_day1_vitals"."No of patients" AS "No of patients",
"derived"."summary_day1_vitals"."No of students" AS "No of students",
"derived"."summary_day1_vitals"."Location" AS "Location",
"derived"."summary_day1_vitals"."Frequency Monitoring" AS "Frequency Monitoring",
"derived"."summary_day1_vitals"."Time1" AS "Time1",
"derived"."summary_day1_vitals"."Time2" AS "Time2",
"derived"."summary_day1_vitals"."Time3" AS "Time3",
"derived"."summary_day1_vitals"."Time4" AS "Time4",
"derived"."summary_day1_vitals"."Time5" AS "Time5",
"derived"."summary_day1_vitals"."Time6" AS "Time6",
"derived"."summary_day1_vitals"."Hypothermia" AS "Hypothermia",
"derived"."summary_day1_vitals"."Temperature 1" AS "Temperature 1",
"derived"."summary_day1_vitals"."Temperature 1 Time" AS "Temperature 1 Time",
"derived"."summary_day1_vitals"."Temperature 2 done" AS "Temperature 2 done",
"derived"."summary_day1_vitals"."Temperature2" AS "Temperature2",
"derived"."summary_day1_vitals"."Temperature2 Time" AS "Temperature2 Time",
"derived"."summary_day1_vitals"."Day" AS "Day"
FROM "derived"."summary_day1_vitals"
UNION ALL
SELECT "derived"."summary_day2_vitals"."Facility Name" AS "Facility Name",
"derived"."summary_day2_vitals"."NeoTreeID" AS "NeoTreeID",
Date("derived"."summary_day2_vitals"."Date") AS "Date",
"derived"."summary_day2_vitals"."Length of stay" AS "Length of stay",
"derived"."summary_day2_vitals"."Neonatal Sepsis Study" AS "Neonatal Sepsis Study",
"derived"."summary_day2_vitals"."Day of the Week" AS "Day of the Week",
"derived"."summary_day2_vitals"."Public Holiday" AS "Public Holiday",
"derived"."summary_day2_vitals"."No of Day Shift Nurses" AS "No of Day Shift Nurses",
"derived"."summary_day2_vitals"."No of Night Shift Nurses" AS "No of Night Shift Nurses",
"derived"."summary_day2_vitals"."No of Countious Shift Nurses" AS "No of Countious Shift Nurses",
"derived"."summary_day2_vitals"."No of patients" AS "No of patients",
"derived"."summary_day2_vitals"."No of students" AS "No of students",
"derived"."summary_day2_vitals"."Location" AS "Location",
"derived"."summary_day2_vitals"."Frequency Monitoring" AS "Frequency Monitoring",
"derived"."summary_day2_vitals"."Time1" AS "Time1",
"derived"."summary_day2_vitals"."Time2" AS "Time2",
"derived"."summary_day2_vitals"."Time3" AS "Time3",
"derived"."summary_day2_vitals"."Time4" AS "Time4",
"derived"."summary_day2_vitals"."Time5" AS "Time5",
"derived"."summary_day2_vitals"."Time6" AS "Time6",
"derived"."summary_day2_vitals"."Hypothermia" AS "Hypothermia",
"derived"."summary_day2_vitals"."Temperature 1" AS "Temperature 1",
"derived"."summary_day2_vitals"."Temperature 1 Time" AS "Temperature 1 Time",
"derived"."summary_day2_vitals"."Temperature 2 done" AS "Temperature 2 done",
"derived"."summary_day2_vitals"."Temperature2" AS "Temperature2",
"derived"."summary_day2_vitals"."Temperature2 Time" AS "Temperature2 Time",
"derived"."summary_day2_vitals"."Day" AS "Day"
FROM "derived"."summary_day2_vitals"
UNION ALL
SELECT "derived"."summary_day3_vitals"."Facility Name" AS "Facility Name",
"derived"."summary_day3_vitals"."NeoTreeID" AS "NeoTreeID",
Date("derived"."summary_day3_vitals"."Date") AS "Date",
"derived"."summary_day3_vitals"."Length of stay" AS "Length of stay",
"derived"."summary_day3_vitals"."Neonatal Sepsis Study" AS "Neonatal Sepsis Study",
"derived"."summary_day3_vitals"."Day of the Week" AS "Day of the Week",
"derived"."summary_day3_vitals"."Public Holiday" AS "Public Holiday",
"derived"."summary_day3_vitals"."No of Day Shift Nurses" AS "No of Day Shift Nurses",
"derived"."summary_day3_vitals"."No of Night Shift Nurses" AS "No of Night Shift Nurses",
"derived"."summary_day3_vitals"."No of Countious Shift Nurses" AS "No of Countious Shift Nurses",
"derived"."summary_day3_vitals"."No of patients" AS "No of patients",
"derived"."summary_day3_vitals"."No of students" AS "No of students",
"derived"."summary_day3_vitals"."Location" AS "Location",
"derived"."summary_day3_vitals"."Frequency Monitoring" AS "Frequency Monitoring",
"derived"."summary_day3_vitals"."Time1" AS "Time1",
"derived"."summary_day3_vitals"."Time2" AS "Time2",
"derived"."summary_day3_vitals"."Time3" AS "Time3",
"derived"."summary_day3_vitals"."Time4" AS "Time4",
"derived"."summary_day3_vitals"."Time5" AS "Time5",
"derived"."summary_day3_vitals"."Time6" AS "Time6",
"derived"."summary_day3_vitals"."Hypothermia" AS "Hypothermia",
"derived"."summary_day3_vitals"."Temperature 1" AS "Temperature 1",
"derived"."summary_day3_vitals"."Temperature 1 Time" AS "Temperature 1 Time",
"derived"."summary_day3_vitals"."Temperature 2 done" AS "Temperature 2 done",
"derived"."summary_day3_vitals"."Temperature2" AS "Temperature2",
"derived"."summary_day3_vitals"."Temperature2 Time" AS "Temperature2 Time",
"derived"."summary_day3_vitals"."Day" AS "Day"
FROM "derived"."summary_day3_vitals";
'''
